version: '3.3'
networks:
  nuchbee:
services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:22
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=password123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
  rest-api-server:
    networks:
      - nuchbee
    container_name: rest-api-server
    restart: "no"
    ports:
      - "8999:8999"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: rest-api/.
  auth:
    networks:
      - nuchbee
    container_name: auth
    restart: always
    ports:
      - "8905:8905"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: auth/.
  bumi_scheduler:
    networks:
      - nuchbee
    container_name: bumi_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: bumi_scheduler/.
  bumi_worker:
    networks:
      - nuchbee
    container_name: bumi_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: bumi_worker/.
  diworker:
    networks:
      - nuchbee
    container_name: diworker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: diworker/.
    depends_on:
      - clickhouse
  herald_server_engine:
    networks:
      - nuchbee
    container_name: herald_server_engine
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HERALD_SERVICE=engine
    build: herald/.
  herald_server_api:
    networks:
      - nuchbee
    container_name: herald_server_api
    restart: always
    ports:
      - "8906:8906"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HERALD_SERVICE=api
    build: herald/.
  katara_service_scheduler:
    networks:
      - nuchbee
    container_name: katara_service_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HX_KATARA_ROLE=scheduler
    build: 
      context: katara/.
      dockerfile: Dockerfile_service
  katara_service_api:
    networks:
      - nuchbee
    container_name: katara_service_api
    restart: always
    ports:
      - "8935:8935"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HX_KATARA_ROLE=api
    build:
      context: katara/.
      dockerfile: Dockerfile_service
    depends_on:
      - rest-api-server
  katara_worker:
    networks:
      - nuchbee
    container_name: katara_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HX_KATARA_ROLE=scheduler
    build: 
      context: katara/.
      dockerfile: Dockerfile_worker
    depends_on:
      - katara_service_scheduler
  resource_discovery_scheduler:
      networks:
        - nuchbee
      container_name: resource_discovery_scheduler
      restart: always
      environment:
        - HX_ETCD_HOST=10.128.0.2
        - HX_ETCD_PORT=2379
      build: deploy/docker_images/resource_discovery/.
      depends_on:
        - rest-api-server
  resource_discovery_worker:
      networks:
        - nuchbee
      container_name: resource_discovery_worker
      restart: always
      environment:
        - HX_ETCD_HOST=10.128.0.2
        - HX_ETCD_PORT=2379
      build: 
        context: deploy/docker_images/resource_discovery/.
        dockerfile: Dockerfile_worker
      depends_on:
        - resource_discovery_scheduler
  metroculus_api:
    networks:
      - nuchbee
    container_name: metroculus_api
    restart: always
    ports:
      - "8969:8969"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build : 
      context: metroculus/.
      dockerfile: metroculus_api/Dockerfile
    depends_on:
      - rest-api-server
  metroculus_scheduler:
    networks:
      - nuchbee
    container_name: metroculus_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: metroculus/.
      dockerfile: metroculus_scheduler/Dockerfile
    depends_on:
      - metroculus_api
  metroculus_worker:
    networks:
      - nuchbee
    container_name: metroculus_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: metroculus/.
      dockerfile: metroculus_worker/Dockerfile
    depends_on:
      - metroculus_scheduler
  insider_api:
    networks:
      - nuchbee
    container_name: insider_api
    restart: always
    ports:
      - "8945:8945"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: insider/.
      dockerfile: insider_api/Dockerfile
    depends_on:
      - rest-api-server
  insider_scheduler:
    networks:
      - nuchbee
    container_name: insider_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: insider/. 
      dockerfile: insider_scheduler/Dockerfile
    depends_on:
      - insider_api
  insider_worker:
    networks:
      - nuchbee
    container_name: insider_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.28.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: insider/.
      dockerfile: insider_worker/Dockerfile
    depends_on:
      - insider_scheduler
  trapper_scheduler:
    networks:
      - nuchbee
    container_name: trapper_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: trapper/.
      dockerfile: trapper_scheduler/Dockerfile
    depends_on:
      - rest-api-server
  trapper_worker:
    networks:
      - nuchbee
    container_name: trapper_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: trapper/.
      dockerfile: trapper_worker/Dockerfile
    depends_on:
      - trapper_scheduler
volumes:
  clickhouse_data:
    driver: local
