version: '3.3'
networks:
  nuchbee:
services:
  rest-api-server:
    networks:
      - nuchbee
    container_name: rest-api-server
    restart: "no"
    ports:
      - "8999:8999"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: rest-api/.
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-rest-api-server:latest
  auth:
    networks:
      - nuchbee
    container_name: auth
    restart: always
    ports:
      - "8905:8905"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: auth/.
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-auth:latest
    depends_on:
      - rest-api-server
  bumi_scheduler:
    networks:
      - nuchbee
    container_name: bumi_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: bumi_scheduler/.
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-bumi_scheduler:latest
    depends_on:
      - auth
  bumi_worker:
    networks:
      - nuchbee
    container_name: bumi_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: bumi_worker/.
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-bumi_worker:latest
    depends_on:
      - auth
  diworker:
    networks:
      - nuchbee
    container_name: diworker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: diworker/.
    image: 2280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-diworker:latest
  herald_server_engine:
    networks:
      - nuchbee
    container_name: herald_server_engine
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HERALD_SERVICE=engine
    build: herald/.
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-herald_server_engine:latest
  herald_server_api:
    networks:
      - nuchbee
    container_name: herald_server_api
    restart: always
    ports:
      - "8906:8906"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HERALD_SERVICE=api
    build: herald/.
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-herald_server_api:latest
  katara_service_scheduler:
    networks:
      - nuchbee
    container_name: katara_service_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HX_KATARA_ROLE=scheduler
    build: 
      context: katara/.
      dockerfile: Dockerfile_service
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-katara_service_scheduler:latest
  katara_service_api:
    networks:
      - nuchbee
    container_name: katara_service_api
    restart: always
    ports:
      - "8935:8935"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HX_KATARA_ROLE=api
    build:
      context: katara/.
      dockerfile: Dockerfile_service
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-katara_service_api:latest
    depends_on:
      - rest-api-server
  katara_worker:
    networks:
      - nuchbee
    container_name: katara_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
      - HX_KATARA_ROLE=scheduler
    build: 
      context: katara/.
      dockerfile: Dockerfile_worker
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-katara_worker:latest
    depends_on:
      - katara_service_scheduler
  resource_discovery_scheduler:
      networks:
        - nuchbee
      container_name: resource_discovery_scheduler
      restart: always
      environment:
        - HX_ETCD_HOST=10.128.0.2
        - HX_ETCD_PORT=2379
      build: deploy/docker_images/resource_discovery/.
      image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-resource_discovery_scheduler:latest
      depends_on:
        - rest-api-server
  resource_discovery_worker:
      networks:
        - nuchbee
      container_name: resource_discovery_worker
      restart: always
      environment:
        - HX_ETCD_HOST=10.128.0.2
        - HX_ETCD_PORT=2379
      build: 
        context: deploy/docker_images/resource_discovery/.
        dockerfile: Dockerfile_worker
      image: 2280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-resource_discovery_worker:latest
      depends_on:
        - resource_discovery_scheduler
  metroculus_api:
    networks:
      - nuchbee
    container_name: metroculus_api
    restart: always
    ports:
      - "8969:8969"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build : 
      context: metroculus/.
      dockerfile: metroculus_api/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-metroculus_api:latest
    depends_on:
      - rest-api-server
  metroculus_scheduler:
    networks:
      - nuchbee
    container_name: metroculus_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: metroculus/.
      dockerfile: metroculus_scheduler/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-metroculus_scheduler:latest
    depends_on:
      - metroculus_api
  metroculus_worker:
    networks:
      - nuchbee
    container_name: metroculus_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: metroculus/.
      dockerfile: metroculus_worker/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-metroculus_worker:latest
    depends_on:
      - metroculus_scheduler
  insider_api:
    networks:
      - nuchbee
    container_name: insider_api
    restart: always
    ports:
      - "8945:8945"
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: insider/.
      dockerfile: insider_api/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-insider_api:latest
    depends_on:
      - rest-api-server
  insider_scheduler:
    networks:
      - nuchbee
    container_name: insider_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: insider/. 
      dockerfile: insider_scheduler/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-insider_scheduler:latest
    depends_on:
      - insider_api
  insider_worker:
    networks:
      - nuchbee
    container_name: insider_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.28.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: insider/.
      dockerfile: insider_worker/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-insider_worker:latest
    depends_on:
      - insider_scheduler
  trapper_scheduler:
    networks:
      - nuchbee
    container_name: trapper_scheduler
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: trapper/.
      dockerfile: trapper_scheduler/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-trapper_scheduler:latest
    depends_on:
      - rest-api-server
  trapper_worker:
    networks:
      - nuchbee
    container_name: trapper_worker
    restart: always
    environment:
      - HX_ETCD_HOST=10.128.0.2
      - HX_ETCD_PORT=2379
    build: 
      context: trapper/.
      dockerfile: trapper_worker/Dockerfile
    image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-trapper_worker:latest
    depends_on:
      - trapper_scheduler
volumes:
  clickhouse_data:
    driver: local
