apiVersion: batch/v1
kind: CronJob
metadata:
  name: bumi-scheduler
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bumi-scheduler
            env:
            - name: HX_ETCD_HOST
              value: "optscale-etcd.optscale.svc.cluster.local"
            - name: HX_ETCD_PORT
              value: "2379"
            image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-bumi_scheduler:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: Never