apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: insider-worker
  name: insider-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: insider-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/nuchbee: "true"
        io.kompose.service: insider-worker
    spec:
      containers:
        - env:
            - name: HX_ETCD_HOST
              value: "optscale-etcd.optscale.svc.cluster.local"
            - name: HX_ETCD_PORT
              value: "2379"
          image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-insider_worker:latest
          name: insider-worker
          resources: {}
      restartPolicy: Always
status: {}
