apiVersion: v1
kind: Pod
metadata:
  name: rest-api-server
  labels:
    io.kompose.service: rest-api-server
spec:
    containers:
      - env:
          - name: HX_ETCD_HOST
            value: "optscale-etcd.optscale.svc.cluster.local"
          - name: HX_ETCD_PORT
            value: "2379"
        image: 280501305789.dkr.ecr.us-east-1.amazonaws.com/optscale-rest-api-server:latest
        name: rest-api-server
        ports:
          - containerPort: 8999
        resources: {}
    restartPolicy: Never
status: {}
