---
- name: Remove log files and users trash
  shell: "rm -rf {{ item }}"
  args:
    warn: false
  with_items:
   - /home/engineer/.ssh
   - /home/engineer/.bash_history
   - /home/engineer/.ansible
   - /home/dts/.ssh
   - /home/dts/.bash_history
   - /home/dts/.ansible
   - /home/user/.ssh
   - /home/user/.bash_history
   - /home/user/.ansible
   - "/home/{{ ansible_ssh_user }}/.ssh"
   - "/home/{{ ansible_ssh_user }}/.bash_history"
   - "/home/{{ ansible_ssh_user }}/.ansible"
   - /root/.ssh
   - /root/.bash_history
   - /root/.ansible
  become: yes

- name: Remove password from engineer user
  user:
    name: "{{ item }}"
    password: "!"
  with_items:
   - engineer
   - user
   - root
  become: yes
