FROM --platform=linux/amd64 optscale-python:latest
WORKDIR /usr/src/app/katara_worker
ENV PYTHONPATH=/usr/src/app/

COPY katara_worker/reports_generators ./reports_generators
COPY katara_worker/*.py ./
CMD ["python", "-u","/usr/src/app/katara_worker/main.py"]
