FROM --platform=linux/amd64 python

WORKDIR /usr/src/app/katara_service
ENV PYTHONPATH /usr/src/app/

COPY katara_service/alembic ./alembic
COPY katara_service/controllers ./controllers
COPY katara_service/handlers ./handlers
COPY katara_service/models ./models
COPY katara_service/*.py ./
COPY katara_service/alembic.template .
COPY katara_service/swagger ./swagger

RUN python -u write_spec.py

CMD ["python", "-u","/usr/src/app/katara_service/main.py"]
EXPOSE 8935
