---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: Add kubernetes key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present
  become: yes

# xenial is always used, because bionic repo doesn't exist yet
- name: Add kubernetes repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
  become: yes

- name: Install kubernetes packages
  apt:
    name: "{{ item }}={{ kubernetes_version }}-*"
    state: present
    update_cache: yes
  become: yes
  loop: "{{ kubernetes_packages }}"

- name: Mark k8s packages for hold (you can safely use apt upgrade on host)
  shell: apt-mark hold {{ item }}
  become: yes
  loop: "{{ kubernetes_packages }}"

- name: Remove swapfile from /etc/fstab
  mount:
    path: none
    fstype: swap
    state: absent
  become: yes

- name: Disable swap
  command: swapoff -a
  become: yes
